---
extends:
  - react-app
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
rules:
  # Typescript
  "@typescript-eslint/explicit-function-return-type": off
  "@typescript-eslint/no-unused-vars": error
  "@typescript-eslint/member-delimiter-style":
    - error
    - multiline:
        delimiter: semi
        requireLast: true
      singleline:
        delimiter: semi
        requireLast: false
  # Es
  semi: error
  eqeqeq: error

